issues:
  max-issues-per-linter: 0
  new: false
  max-same-issues: 0
  fix: true

output:
  print-issued-lines: false
  print-linter-name: true
  uniq-by-line: false
  path-prefix: ''
  sort-results: true

linters:
  enable-all: true
  disable:
    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    # Don't care for
    - cyclop
    - errorlint
    - exhaustive
    - exhaustruct
    - funlen
    - gocognit
    - godox
    - gomnd
    - ireturn
    - lll
    - maintidx
    - nestif
    - paralleltest
    - tagliatelle
    - testpackage
    - thelper
    - varnamelen
    - wrapcheck
    - dupl
    # Temp
    - goerr113
    - contextcheck
